# Generated by Django 3.1.4 on 2020-12-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('values', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('E', 'easy'), ('M', 'medium'), ('H', 'hard'), ('N', 'N/A')], default='N', max_length=1)),
                ('num_attempts', models.PositiveBigIntegerField()),
                ('num_solved', models.PositiveBigIntegerField()),
                ('average_time', models.DurationField()),
                ('best_time', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
